---

- name: Install Splunk
  hosts: splunkenterprise
  serial: 6
  become: true
  tasks:
    - name: Create /opt/splunk
      file:
        path: /opt/splunk
        state: directory
    - name: Download Sources
      unarchive:
        src: "{{ src }}"
        dest: "/opt/"
        mode: 0755
        remote_src: yes
        creates: /opt/splunk/etc/system/local
    - name: This edits user-seed.conf and adds a username
      ini_file:
        dest: "/opt/splunk/etc/system/local/user-seed.conf"
        section: "user_info"
        option: "USERNAME"
        value: "{{ splunk_username }}"
    - name: This edits user-seed.conf and adds a password
      ini_file:
        dest: "/opt/splunk/etc/system/local/user-seed.conf"
        section: "user_info"
        option: "HASHED_PASSWORD"
        value: "{{ splunk_password }}"
    - name: This will enable SSL on all Splunk Enterprise instances
      ini_file:
        dest: "/opt/splunk/etc/system/local/web.conf"
        section: "settings"
        option: "enableSplunkWebSSL"
        value: "true"
    - name: This command will run splunk start
      command:
        cmd: /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt
    - name: Enable Boot Start
      command: /opt/splunk/bin/splunk enable boot-start
- name: Install SplunkForwarder
  hosts: uf
  tasks:
    - name: Create /opt/splunkforwarder
      file:
        path: /opt/splunkforwarder
        state: directory
      become: true
    - name: Download Sources
      unarchive:
        src: "{{ src }}"
        dest: "/opt/"
        mode: 0755
        remote_src: yes
        creates: /opt/splunkforwarder/etc/system/local
      become: true
    - name: This command will start the splunk forwarder
      command:
        cmd: /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt
      become: true
